name: qazo_namoz
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.2
  dio: ^5.4.2+1
  flutter_bloc: ^8.1.5
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.9.0
  get_it: ^7.6.8
  logger: ^2.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  lottie: ^3.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/icons/
    - assets/images/
    - assets/sound/
